# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_ekstraksi.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from RSA import Ui_RSA
from Elgamal import Ui_Elgamal

class Ui_ekstraksi(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 700)
        Dialog.setStyleSheet("")
        self.background = QtWidgets.QLabel(Dialog)
        self.background.setGeometry(QtCore.QRect(0, 0, 601, 701))
        self.background.setAutoFillBackground(False)
        self.background.setStyleSheet("background-image: url(:/newPrefix/Users/user/Downloads/Premium Vector _ Circuit board Motherboard_ Blue technology background.jpeg);")
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("../../../../Users/user/Downloads/Premium Vector _ Circuit board Motherboard_ Blue technology background.jpeg"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.title_eks = QtWidgets.QLabel(Dialog)
        self.title_eks.setGeometry(QtCore.QRect(240, 90, 141, 41))
        self.title_eks.setStyleSheet("font-size:20pt; color:rgb(255, 255, 255);\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"")
        self.title_eks.setObjectName("title_eks")
        self.RSA_button = QtWidgets.QPushButton(Dialog)
        self.RSA_button.setGeometry(QtCore.QRect(180, 260, 95, 61))
        self.RSA_button.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 85, 127), stop:1 rgba(0, 0, 0)); font-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255); \n"
"")
        self.RSA_button.setObjectName("RSA_button")
        self.Elgamal_button = QtWidgets.QPushButton(Dialog)
        self.Elgamal_button.setGeometry(QtCore.QRect(350, 260, 95, 61))
        self.Elgamal_button.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 85, 127), stop:1 rgba(0, 0, 0)); font-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255); ")
        self.Elgamal_button.setObjectName("Elgamal_button")
        self.backbutton = QtWidgets.QPushButton(Dialog)
        self.backbutton.setGeometry(QtCore.QRect(30, 630, 81, 31))
        self.backbutton.setStyleSheet("font:11pt\n")
        self.backbutton.setObjectName("backbutton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.RSA_button.clicked.connect(self.open_RSA)
        self.Elgamal_button.clicked.connect(self.open_Elgamal)
        self.backbutton.clicked.connect(self.open_startwindow)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title_eks.setText(_translate("Dialog", "EKSTRAKSI"))
        self.RSA_button.setText(_translate("Dialog", "RSA"))
        self.Elgamal_button.setText(_translate("Dialog", "EL-GAMAL"))
        self.backbutton.setText(_translate("Dialog", "<-back"))
    def open_RSA(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_RSA()
        self.ui.setupUi(self.window)
        self.window.show()

    def open_Elgamal(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Elgamal()
        self.ui.setupUi(self.window)
        self.window.show()
        
    def open_startwindow(self):
        """Fungsi untuk membuka jendela start"""
        from startwindow import Ui_startwindow
        self.window = QtWidgets.QDialog()
        self.ui = Ui_startwindow()
        self.ui.setupUi(self.window)
        self.window.show()

import terbaru_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_ekstraksi()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
