# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RSA.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RSA(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 700)
        self.Dekripsi_button = QtWidgets.QPushButton(Dialog)
        self.Dekripsi_button.setGeometry(QtCore.QRect(410, 260, 110, 61))
        self.Dekripsi_button.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 85, 127), stop:1 rgba(0, 0, 0)); font-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255); ")
        self.Dekripsi_button.setObjectName("Dekripsi_button")
        self.title_rsa = QtWidgets.QLabel(Dialog)
        self.title_rsa.setGeometry(QtCore.QRect(290, 130, 47, 31))
        self.title_rsa.setStyleSheet("color:rgb(255, 255, 255); font: 20pt \"MS Shell Dlg 2\";")
        self.title_rsa.setObjectName("title_rsa")
        self.Enkripsi_button = QtWidgets.QPushButton(Dialog)
        self.Enkripsi_button.setGeometry(QtCore.QRect(120, 260, 110, 61))
        self.Enkripsi_button.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 85, 127), stop:1 rgba(0, 0, 0)); font-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255); \n"
"")
        self.Enkripsi_button.setObjectName("Enkripsi_button")
        self.ekstrakRSA_button = QtWidgets.QPushButton(Dialog)
        self.ekstrakRSA_button.setGeometry(QtCore.QRect(265, 260, 111, 61))
        self.ekstrakRSA_button.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 85, 127), stop:1 rgba(0, 0, 0)); font-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255); ")
        self.ekstrakRSA_button.setObjectName("ekstrakselRSA_button")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(90, 470, 47, 13))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.rsa_background = QtWidgets.QLabel(Dialog)
        self.rsa_background.setGeometry(QtCore.QRect(0, 0, 600, 700))
        self.rsa_background.setStyleSheet("background-image:url(:/newPrefix/Users/user/Downloads/Free Vector _ Gradient geometric blue technology background.jpeg);\n"
"image:url(:/newPrefix/Users/user/Downloads/Locks Silhouette Vector PNG, Black Lock Icon, Lock Icons, Black Icons, Black Lock PNG Image For Free Download.jpeg)")
        self.rsa_background.setText("")
        self.rsa_background.setPixmap(QtGui.QPixmap("../../../../Users/user/Downloads/Premium Vector _ Circuit board Motherboard_ Blue technology background.jpeg"))
        self.rsa_background.setScaledContents(True)
        self.rsa_background.setObjectName("rsa_background")
        self.rsa_background.raise_()
        self.Dekripsi_button.raise_()
        self.title_rsa.raise_()
        self.Enkripsi_button.raise_()
        self.label_2.raise_()
        self.ekstrakRSA_button.raise_()
        self.backbutton = QtWidgets.QPushButton(Dialog)
        self.backbutton.setGeometry(QtCore.QRect(30, 630, 81, 31))
        self.backbutton.setStyleSheet("font:11pt\n")
        self.backbutton.setObjectName("backbutton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.Enkripsi_button.clicked.connect(self.open_pembangkitankunciRSA)
        self.Dekripsi_button.clicked.connect(self.open_dekripsiRSA)
        self.ekstrakRSA_button.clicked.connect(self.open_ekstrakRSA)
        self.backbutton.clicked.connect(self.open_newekstrak)


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Dekripsi_button.setText(_translate("Dialog", "DEKRIPSI"))
        self.title_rsa.setText(_translate("Dialog", "RSA"))
        self.Enkripsi_button.setText(_translate("Dialog", "ENKRIPSI"))
        self.ekstrakRSA_button.setText(_translate("Dialog", "EKSTRAK"))
        self.backbutton.setText(_translate("Dialog", "<-back"))

    def open_pembangkitankunciRSA(self):
        """Fungsi untuk membuka jendela pembangkitanRSA"""
        from Pembangkitankunci import Ui_pembangkitanRSA
        self.window = QtWidgets.QDialog()
        self.ui = Ui_pembangkitanRSA()
        self.ui.setupUi(self.window)
        self.window.exec_()
  
    def open_dekripsiRSA(self):
        """Fungsi untuk membuka jendela dekripsi"""
        from dekripsiRSA import Ui_Dekripsi
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Dekripsi()
        self.ui.setupUi(self.window)
        self.window.show()
        
    def open_newekstrak(self):
        """Fungsi untuk membuka jendela start"""
        from new_ekstraksi import Ui_ekstraksi
        self.window = QtWidgets.QDialog()
        self.ui = Ui_ekstraksi()
        self.ui.setupUi(self.window)
        self.window.show()
        
    def open_ekstrakRSA(self):
        from ekstrakRSA import Ui_EkstraksiRSA
        self.window = QtWidgets.QDialog()
        self.ui = Ui_EkstraksiRSA()
        self.ui.setupUi(self.window)
        self.window.show()
        pass
    
import bgrsa_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_RSA()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
