# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_startwindow(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Apps")
        Dialog.resize(600, 700)
        Dialog.setStyleSheet(" font-color:rgb(255, 255, 255); color:rgb(255, 255, 255)")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 600, 700))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/Users/user/Downloads/Premium Vector _ Cyber attack.jpeg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.Title = QtWidgets.QLabel(Dialog)
        self.Title.setGeometry(QtCore.QRect(215, 65, 481, 41))
        self.Title.setStyleSheet("font-size:20pt;")
        self.Title.setObjectName("Title")
        self.Ekstrakbutton = QtWidgets.QPushButton(Dialog)
        self.Ekstrakbutton.setGeometry(QtCore.QRect(150, 250, 120, 73))
        self.Ekstrakbutton.setStyleSheet("color:rgb(255, 255, 255); background-color:rgb(6, 44, 45); font-size:12pt;")
        self.Ekstrakbutton.setObjectName("Ekstrakbutton")
        self.Embeddbutton = QtWidgets.QPushButton(Dialog)
        self.Embeddbutton.setGeometry(QtCore.QRect(350, 250, 120, 73))
        self.Embeddbutton.setStyleSheet("color:rgb(255, 255, 255); background-color:rgb(6, 44, 45); font-size:12pt;")
        self.Embeddbutton.setObjectName("Embeddbutton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.Ekstrakbutton.clicked.connect(self.open_ekstraksi)
        self.Embeddbutton.clicked.connect(self.open_embedded)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Apps"))
        self.Title.setText(_translate("Dialog", "KRIPTO STEGO"))
        self.Ekstrakbutton.setText(_translate("Dialog", "EKSTRAKSI"))
        self.Embeddbutton.setText(_translate("Dialog", "EMBED"))

    def open_ekstraksi(self):
        """Fungsi untuk membuka jendela ekstraksi"""
        from new_ekstraksi import Ui_ekstraksi
        self.window = QtWidgets.QDialog()
        self.ui = Ui_ekstraksi()
        self.ui.setupUi(self.window)
        self.window.show()
    
    def open_embedded(self):
        """Fungsi untuk membuka jendela embedded"""
        from embedded_message import Ui_Embedd
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Embedd()
        self.ui.setupUi(self.window)
        self.window.show()

import new_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_startwindow()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
